service: aws-node-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /
          method: get
          
plugins:
  - serverless-offline-lambda
  - serverless-offline
  - serverless-plugin-typescript
